[2024-04-01T15:07:24.584+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_osm_farmland.load_farmland_from_api manual__2024-04-01T15:03:05.841480+00:00 [queued]>
[2024-04-01T15:07:24.593+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_osm_farmland.load_farmland_from_api manual__2024-04-01T15:03:05.841480+00:00 [queued]>
[2024-04-01T15:07:24.593+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-01T15:07:24.609+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_farmland_from_api> on 2024-04-01 15:03:05.841480+00:00
[2024-04-01T15:07:24.615+0000] {standard_task_runner.py:60} INFO - Started process 2882 to run task
[2024-04-01T15:07:24.619+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_osm_farmland', 'load_farmland_from_api', 'manual__2024-04-01T15:03:05.841480+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/extract_file_data_from_osm.py', '--cfg-path', '/tmp/tmpe0h4on99']
[2024-04-01T15:07:24.621+0000] {standard_task_runner.py:88} INFO - Job 90: Subtask load_farmland_from_api
[2024-04-01T15:07:24.673+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_osm_farmland.load_farmland_from_api manual__2024-04-01T15:03:05.841480+00:00 [running]> on host 84497f327267
[2024-04-01T15:07:24.783+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_osm_farmland' AIRFLOW_CTX_TASK_ID='load_farmland_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T15:03:05.841480+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T15:03:05.841480+00:00'
[2024-04-01T15:07:46.259+0000] {collection.py:293} WARNING - Skipping field nodes: invalid type 13
[2024-04-01T15:07:54.870+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_file_data_from_osm.py", line 69, in load_farmland_from_api
    upload_geodataframe_to_gcs(farm_gdf, GCS_BUCKET, GCS_INTERMEDIATE_PATH)
  File "/opt/airflow/dags/utils.py", line 15, in upload_geodataframe_to_gcs
    geojson_bytes = geodataframe.to_file(destination_blob_path,index=False,Driver='GeoJSON').encode('latin-1')  # Consider compression if needed
AttributeError: 'NoneType' object has no attribute 'encode'
[2024-04-01T15:07:54.888+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=extract_osm_farmland, task_id=load_farmland_from_api, execution_date=20240401T150305, start_date=20240401T150724, end_date=20240401T150754
[2024-04-01T15:07:54.903+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 90 for task load_farmland_from_api ('NoneType' object has no attribute 'encode'; 2882)
[2024-04-01T15:07:54.941+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T15:07:54.965+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
